### ISSUE TITLE
[Bug]: Foremost tools 

### ISSUE THREAD

**Issue by Sakada-lim** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#397]
### Name of Bug

Multi selection allow in options field

### What Happened?

Refer to PTGUI Project Final Report

### Steps to Reproduce

Refer to PTGUI Project Final Report

**Comment by bradleybogg** [comment]
From the final report as above description doesn't include:

Foremost is a console program to recover files based on their headers, footers, and internal data structures. Foremost can work on image files, such as those generated by dd, Safeback, Encase, or similar programs, or directly on a drive. A configuration file can specify the headers and footers or use command line switches to select built-in file types.
Foremost was tested with a dd-generated file containing eight jpeg images.


Write All Headers Error | When the the 'Write All Headers' checkbox is selected the incorrect command is issued at the command line and the scan produces an incorrect result. The option -d is written in the command line instead of -a. 

Quiet/Verbose Checkbox Error | The Foremost DDT GUI allows users to select Quiet and Verbose modes simultaneously. These options contradict each other. The GUI should select either one of these two options; both options should not be available for selection at the same time. 

White Screen Error | When the user selects the Quiet or Verbose Checkboxes 3 times the DDT application displays an all white screen with only the Title Header visible.
