### ISSUE TITLE
[Bug]: DNSmap tools

### ISSUE THREAD

**Issue by Sakada-lim** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#402]
### Name of Bug

Advance mode and syntax error

### Description

Usage of advance mode product error

### Steps to Reproduce

Refer to the PTGUI project Final report

**Comment by v-xl** [comment]
I'm just adding a brief summary of the individual bugs/issues mentioned in the reported for this tool:
1.	Spelling errors in the tooltip text
2.	When selecting an external wordlist, the DDT GUI uses the incorrect command -S instead of -w.
3.	When selecting results output to a CSV file, the DDT GUI uses the incorrect command -s instead of -c.
4.	When selecting an IP address to ignore, the DDT GUI uses the incorrect command -t instead of -i.

**Comment by gangamarx** [comment]
Above issues have been checked and confirmed working correctly.
